name: GitHub Actions Security

on:
  pull_request:
  push:
    branches:
      - main
      - master

permissions:
  contents: read

jobs:
  actions-security:
    name: Check workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install aqua tools
        uses: aquaproj/aqua-installer@11dd79b4e498d471a9385aa9fb7f62bb5f52a73c # v4.0.4
        with:
          aqua_version: v2.56.6

      - name: Check action pinning
        run: pinact run --check
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Audit workflows
        run: zizmor --format github .
        env:
          GH_TOKEN: ${{ github.token }}
